import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../styles/fontSize.css";
import App from "./App";
import { Toaster } from "react-hot-toast";
import { Navbar } from "@/components/Layouts/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <App>{children}</App>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
